from reportlab.lib.pagesizes import A4
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.lib import colors
from reportlab.lib.enums import TA_CENTER
import os


# Folder where PDFs will be stored
REPORTS_FOLDER = os.path.join(
    os.path.dirname(os.path.abspath(__file__)),
    "reports"
)

os.makedirs(REPORTS_FOLDER, exist_ok=True)


styles = getSampleStyleSheet()

title_style = styles["Title"]
title_style.alignment = TA_CENTER

heading_style = styles["Heading2"]
normal_style = styles["BodyText"]


def create_report(filename, title, report_type, summary):
    filepath = os.path.join(REPORTS_FOLDER, filename)

    doc = SimpleDocTemplate(
        filepath,
        pagesize=A4,
        rightMargin=50,
        leftMargin=50,
        topMargin=50,
        bottomMargin=50
    )

    story = []

    story.append(Paragraph("NETWORK INTRUSION DETECTION SYSTEM", title_style))
    story.append(Spacer(1, 20))

    story.append(Paragraph(title, heading_style))
    story.append(Spacer(1, 10))

    story.append(
        Paragraph(
            f"<b>Report Type:</b> {report_type}",
            normal_style
        )
    )

    story.append(Spacer(1, 10))

    story.append(
        Paragraph(
            f"<b>Status:</b> Completed",
            normal_style
        )
    )

    story.append(Spacer(1, 10))

    story.append(
        Paragraph(
            f"<b>Summary:</b> {summary}",
            normal_style
        )
    )

    story.append(Spacer(1, 30))

    story.append(
        Paragraph(
            "This report was generated by the Network Intrusion Detection System.",
            normal_style
        )
    )

    doc.build(story)

    print(f"Created: {filepath}")


# Report 1
create_report(
    "network_security_20260906.pdf",
    "Network Security Report",
    "Security Analysis",
    "Comprehensive network security analysis"
)

# Report 2
create_report(
    "threat_detection_20260905.pdf",
    "Threat Detection Report",
    "Threat Analysis",
    "Threat detection and analysis summary"
)

# Report 3
create_report(
    "intrusion_analysis_20260904.pdf",
    "Intrusion Analysis Report",
    "Intrusion Detection",
    "Intrusion detection system analysis"
)

# Report 4
create_report(
    "network_traffic_20260903.pdf",
    "Network Traffic Report",
    "Traffic Analysis",
    "Network traffic pattern analysis"
)


print("\nAll reports created successfully!")